### ISSUE TITLE
Vert.x 3 service deployment

### ISSUE THREAD

**Issue by Jotschi** [englishtown/vertx-jersey#25]
I'm trying to deploy a verticle that contains a simply rest resource using the [maven service factory](https://github.com/vert-x3/maven-service-factory/). The maven service factory can be used to deploy verticles that were packages and deployed in a maven repository. The factory will download the artifact and startup a verticle that is contained in the jar.

```
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;

import com.englishtown.vertx.hk2.HK2MavenVerticleFactory;

public class Runner {
	private static final Vertx vertx = Vertx.vertx();

	public static void main(String[] args) {
                // Custom HK2 Maven Verticle Factory (see below)
		vertx.registerVerticleFactory(new HK2MavenVerticleFactory());

		JsonObject verticleConf = new JsonObject();
		verticleConf.put("resources", new JsonArray().add("my.module.resources"));
		verticleConf.put("port", 8000);
		
		DeploymentOptions rootOptions = new DeploymentOptions().setConfig(verticleConf);
		vertx.deployVerticle("service-hk2:my:module:0.1.0-SNAPSHOT", rootOptions);

	}
}
```

I added a HK2 enabled maven verticle factory to the HK2 project. If i did not use this verticle factory the default JavaVerticleFactory would be used and thus no dependency injection would occur.

```
package com.englishtown.vertx.hk2;

import io.vertx.core.DeploymentOptions;
import io.vertx.maven.MavenVerticleFactory;

public class HK2MavenVerticleFactory extends MavenVerticleFactory {

	@Override
	public String prefix() {
		return "service-hk2";
	}

	@Override
	public String resolve(String identifier,
			DeploymentOptions deploymentOptions, ClassLoader classLoader)
			throws Exception {
		String resolved = super.resolve(identifier, deploymentOptions,
				classLoader);
		return HK2VerticleFactory.PREFIX + ":" + resolved;
	}

}
```

I get the following exception:

```
Nov 17, 2014 11:05:27 AM com.englishtown.vertx.hk2.HK2VerticleLoader
SEVERE: Class com.englishtown.vertx.hk2.BootstrapBinder does not implement Binder.
Nov 17, 2014 11:05:27 AM io.vertx.core.impl.DeploymentManager
SEVERE: A MultiException has 1 exceptions.  They are:
1. org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=JerseyServer,parent=JerseyVerticle,qualifiers={},position=0,optional=false,self=false,unqualified=null,258091697)

MultiException stack 1 of 1
org.glassfish.hk2.api.UnsatisfiedDependencyException: There was no object available for injection at SystemInjecteeImpl(requiredType=JerseyServer,parent=JerseyVerticle,qualifiers={},position=0,optional=false,self=false,unqualified=null,258091697)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:74)
	at org.jvnet.hk2.internal.Utilities.justCreate(Utilities.java:1007)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.create(ServiceLocatorImpl.java:884)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:976)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:968)
	at com.englishtown.vertx.hk2.HK2VerticleLoader.createRealVerticle(HK2VerticleLoader.java:166)
	at com.englishtown.vertx.hk2.HK2VerticleLoader.createRealVerticle(HK2VerticleLoader.java:124)
	at com.englishtown.vertx.hk2.HK2VerticleLoader.start(HK2VerticleLoader.java:75)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$99(DeploymentManager.java:424)
	at io.vertx.core.impl.DeploymentManager$$Lambda$4/195984832.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$10(ContextImpl.java:230)
	at io.vertx.core.impl.ContextImpl$$Lambda$5/1138410383.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Jotschi** [comment]
Just a quick update. I was not able to resolve this issue or workaround it. But the problem itself is no longer important for me. You may close the issue if you want to.

**Comment by adrianluisgonzalez** [comment]
I think the latest ext-hk2 SNAPSHOT resolves this issue.
https://github.com/englishtown/vertx-hk2/commit/ea516df95cfec67b5bfcc0e173bb495b3b250f72

I tried running your jersey-service-test and it ran fine.  I also tried uncommenting `options.setIsolationGroup("A");` and it also worked fine.
