### ISSUE TITLE
vertx runzip fails with java.lang.ClassNotFoundException: javax.inject.Provider

### ISSUE THREAD

**Issue by w0mbat** [englishtown/vertx-jersey#27]
Hey folks,

I just tried to run the jackson example version 2.7.1 via:
```mvn clean install``` and ```vertx runzip target/vertx-jersey-examples-jackson-2.7.1-mod.zip```.

It fails with:

```Failed in deploying module from zip 
java.lang.NoClassDefFoundError: javax/inject/Provider
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getConstructor0(Class.java:3067)
	at java.lang.Class.newInstance(Class.java:408)
	at org.vertx.java.platform.impl.java.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:57)
	at org.vertx.java.platform.impl.DefaultPlatformManager$21.run(DefaultPlatformManager.java:1748)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: javax.inject.Provider
	at org.vertx.java.platform.impl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:127)
	at org.vertx.java.platform.impl.ModuleClassLoader.loadClass(ModuleClassLoader.java:108)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more```

Any ideas?

Best regards,

Daniel

**Comment by adrianluisgonzalez** [comment]
I'll close this unless you have anything else to add.
